# Generated by Django 6.0.3 on 2026-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
