import requests
import base64
import uuid

def create_pull_request(user_token, repo_full_name, file_path, fixed_code, commit_message):
    """
    Automates the full GitHub GitOps flow:
    1. Get default branch SHA.
    2. Create a new fix branch.
    3. Get existing file SHA (if any).
    4. Commit the new code to the new branch.
    5. Open a Pull Request.
    """
    headers = {
        "Authorization": f"token {user_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    base_url = f"https://api.github.com/repos/{repo_full_name}"

    try:
        # Step 1: Get repo details to find default branch
        repo_data = requests.get(base_url, headers=headers).json()
        default_branch = repo_data.get("default_branch", "main")

        # Get default branch SHA
        ref_url = f"{base_url}/git/refs/heads/{default_branch}"
        ref_data = requests.get(ref_url, headers=headers).json()
        base_sha = ref_data["object"]["sha"]

        # Step 2: Create a new branch
        new_branch_name = f"snapit-fix-{uuid.uuid4().hex[:8]}"
        create_ref_url = f"{base_url}/git/refs"
        branch_payload = {
            "ref": f"refs/heads/{new_branch_name}",
            "sha": base_sha
        }
        requests.post(create_ref_url, headers=headers, json=branch_payload).raise_for_status()

        # Step 3: Get current file SHA (if it exists)
        content_url = f"{base_url}/contents/{file_path}"
        file_sha = None
        # Check on the new branch
        content_response = requests.get(f"{content_url}?ref={new_branch_name}", headers=headers)
        if content_response.status_code == 200:
            file_sha = content_response.json().get("sha")

        # Step 4: PUT the updated file content
        encoded_content = base64.b64encode(fixed_code.encode()).decode()
        put_payload = {
            "message": commit_message,
            "content": encoded_content,
            "branch": new_branch_name
        }
        if file_sha:
            put_payload["sha"] = file_sha
        
        requests.put(content_url, headers=headers, json=put_payload).raise_for_status()

        # Step 5: Open a Pull Request
        pull_url = f"{base_url}/pulls"
        pr_payload = {
            "title": commit_message,
            "head": new_branch_name,
            "base": default_branch,
            "body": "This PR was automatically generated by Snap.it AI Debugger."
        }
        pr_response = requests.post(pull_url, headers=headers, json=pr_payload).json()
        
        return pr_response.get("html_url")

    except Exception as e:
        print(f"[GITHUB_SERVICE_ERROR] {str(e)}")
        return None
